# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

%bcond_with v4l2

Name:       gst-plugins-good1.0

# >> macros
# << macros

Summary:    GStreamer streaming media framework good plug-ins
Version:    1.4.0
Release:    1
Group:      Applications/Multimedia
License:    LGPL
URL:        http://gstreamer.freedesktop.org/
Source0:    http://gstreamer.freedesktop.org/src/%{name}/%{name}-%{version}.tar.bz2
BuildRequires:  pkgconfig(orc-0.4) >= 0.4.18
BuildRequires:  pkgconfig(speex)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libsoup-2.4)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(gstreamer-1.0) >= 1.4.0
BuildRequires:  pkgconfig(gstreamer-plugins-base-1.0) >= 1.4.0
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(taglib)
BuildRequires:  pkgconfig(flac)
BuildRequires:  pkgconfig(gudev-1.0)
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  libjpeg-devel
BuildRequires:  python-devel
BuildRequires:  gettext-devel

%description
GStreamer Good Plug-ins is a collection of well-supported plug-ins of good 
quality and under the LGPL license.


%prep
%setup -q -n %{name}-%{version}/gst-plugins-good

# >> setup
# << setup

%build
# >> build pre
export NOCONFIGURE="1"
%autogen
# << build pre

%configure --disable-static \
    --with-package-name='MeeGo GStreamer Plugins Good package' \
    --with-package-origin='http://www.meego.com' \
    --enable-experimental \
    --disable-examples \

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# The video4linux plugin causes a crash on startup on some platforms,
# make it opt in until that is resolved.
%if !%{with v4l2}
rm -rf %{buildroot}/%{_libdir}/gstreamer-1.0/libgstvideo4linux2.so
%endif

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
# Equaliser presets
%{_datadir}/gstreamer-1.0/presets/
%{_libdir}/gstreamer-1.0/*.so
%{_datadir}/gstreamer-1.0/presets/
%{_datadir}/locale/*
# << files
